name: Maven CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
 
    - name: compile
      run: mvn clean install
 
    - name: package
      run: mvn package
 
    - name: unit test
      run: mvn test
 
    - name: working directory
      run: pwd
 
    - name: list the current directory
      run: ls -a

    - name: what is in target folder
      run: |
        cd target
        ls

    - name: analize with sonarcloud
      run: mvn verify sonar:sonar -Dsonar.projectKey=ishita-ct -Dsonar.organization=ishitact -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build, tag, and push apache image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: apache-registry
        IMAGE_TAG: apache_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f /home/runner/work/java-app/java-app/Apache/dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Build, tag, and push tomcat image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tomcat-registry
        IMAGE_TAG: tomcat_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f /home/runner/work/java-app/java-app/tomcat/dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        
    - name: Deploy apache image to public ec2
      uses: appleboy/ssh-action@master
      with:
        host: 3.237.254.197
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo apt install awscli -y
          sudo aws configure set aws_access_key_id "${{ secrets.ACCESS_KEY_ID }}"
          sudo aws configure set aws_secret_access_key "${{ secrets.SECRET_ACCESS_KEY }}"
          sudo aws configure set region "us-east-1"
          sudo aws configure set output json
          sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 741768617807.dkr.ecr.us-east-1.amazonaws.com
          sudo docker pull 741768617807.dkr.ecr.us-east-1.amazonaws.com/apache-registry:apache_image
          sudo docker run -i -t -d -p 80:80 741768617807.dkr.ecr.us-east-1.amazonaws.com/apache-registry:apache_image sh 

    - name: Deploy tomcat image to private ec2
      uses: appleboy/ssh-action@master
      with:
        host: 10.0.2.204
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        proxy_host: 3.237.254.197
        proxy_username: ubuntu
        proxy_key: ${{ secrets.SSH_KEY }}
        proxy_port: 22
        script: |
          sudo apt install awscli -y
          sudo aws configure set aws_access_key_id "${{ secrets.ACCESS_KEY_ID }}"
          sudo aws configure set aws_secret_access_key "${{ secrets.SECRET_ACCESS_KEY }}"
          sudo aws configure set region "us-east-1"
          sudo aws configure set output json
          sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 741768617807.dkr.ecr.us-east-1.amazonaws.com
          sudo docker pull 741768617807.dkr.ecr.us-east-1.amazonaws.com/tomcat-registry:tomcat_image
          sudo docker run -i -t -d -p 8080:8080 741768617807.dkr.ecr.us-east-1.amazonaws.com/tomcat-registry:tomcat_image sh
